### ISSUE TITLE
500 error on search

### ISSUE THREAD

**Issue by abitrolly** [osm-by/OpenStreetMap.by#37]
Search is broken. The underlying XHR request to the url below gives error 500.

https://www.openstreetmap.by/?request=geocode&lat=53.907169&lon=27.57946&zoom=8&text=%D0%BA%D0%B0%D0%BB%D1%8C%D0%B2%D0%B0%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F+21

![image](https://user-images.githubusercontent.com/8781107/160844157-32b39958-52fe-4cc5-84e1-5e23f28e74fc.png)

**Comment by tbicr** [comment]
```webapp_1      | QUERY FAILURE:  
webapp_1      | select
webapp_1      |     "addr:street", "addr:housenumber", "name", "name:ru", "name:be", "place", "shop", "amenity", "ref", "admin_level", "osm_id", "building",
webapp_1      |     ST_AsGeoJSON(ST_Expand(ST_Transform(way,4326),0)) as way,
webapp_1      |     ST_Distance(way, ST_Transform(ST_GeomFromText('POINT(27.579460 53.907169)',4326),900913)) as distance
webapp_1      | from planet_osm_polygon
webapp_1      | where
webapp_1      |     (
webapp_1      |     "addr:street" in (E'кальварийская улица', E'Кальварийская улица', E'Кальварийская ул.') and
webapp_1      |     ("addr:housenumber" in (E'21'))
webapp_1      |     
webapp_1      |     )
webapp_1      | union
webapp_1      | select
webapp_1      |     "addr:street", "addr:housenumber", "name", "name:ru", "name:be", "place", "shop", "amenity", "ref", "admin_level", "osm_id", "building",
webapp_1      |     ST_AsGeoJSON(ST_Expand(ST_Transform(way,4326),0.0005)) as way,
webapp_1      |     ST_Distance(way, ST_Transform(ST_GeomFromText('POINT(27.579460 53.907169)',4326),900913)) as distance
webapp_1      | from planet_osm_point
webapp_1      | where
webapp_1      |     (
webapp_1      |     "addr:street" in (E'кальварийская улица', E'Кальварийская улица', E'Кальварийская ул.') and
webapp_1      |     ("addr:housenumber" in (E'21'))
webapp_1      |     
webapp_1      |     )
webapp_1      | order by distance limit 20;
webapp_1      | Traceback (most recent call last):
webapp_1      |   File "/app/venv/lib/python3.8/site-packages/web/application.py", line 280, in process
webapp_1      |     return self.handle()
webapp_1      |   File "/app/venv/lib/python3.8/site-packages/web/application.py", line 271, in handle
webapp_1      |     return self._delegate(fn, self.fvars, args)
webapp_1      |   File "/app/venv/lib/python3.8/site-packages/web/application.py", line 517, in _delegate
webapp_1      |     return handle_class(cls)
webapp_1      |   File "/app/venv/lib/python3.8/site-packages/web/application.py", line 495, in handle_class
webapp_1      |     return tocall(*args)
webapp_1      |   File "/app/index.py", line 45, in GET
webapp_1      |     return handler()
webapp_1      |   File "/app/index.py", line 33, in handler
webapp_1      |     resp, ctype, content = face_main(data)
webapp_1      |   File "/app/index.py", line 602, in face_main
webapp_1      |     a = {"results": geocoder_geocode(text, (lon, lat))}
webapp_1      |   File "/app/index.py", line 393, in geocoder_geocode
webapp_1      |     descr = postgis_query_geojson(req)
webapp_1      |   File "/app/index.py", line 179, in postgis_query_geojson
webapp_1      |     names = [q[0] for q in database_cursor.description]
webapp_1      | TypeError: 'NoneType' object is not iterable
```

**Comment by abitrolly** [comment]
Does that mean that the query executed successfully, but returned no rows?

**Comment by tbicr** [comment]
yep, there are ` QUERY FAILURE:  `  before first line

**Comment by tbicr** [comment]
I think query failed and it can be reason null in description

**Comment by abitrolly** [comment]
@tbicr did anything new pop up after merging #38? Or should we setup #39 first?
